// Skip any YouTube Ads. Click on the bookmarklet when there's a annoying ad on YouTube.
javascript:  if(document.getElementsByClassName("video-ads")[0].innerHTML !==""){  var banner = false;  for(var i = 0; i < document.getElementsByClassName("ytp-ad-overlay-close-button").length; i++){ document.getElementsByClassName("ytp-ad-overlay-close-button")[i].click(); banner = true;}  if(banner === false){ document.getElementsByClassName("html5-main-video")[0].currentTime = document.getElementsByClassName("html5-main-video")[0].duration; document.getElementsByClassName("ytp-ad-skip-button")[0].click();}  } void 0;
// DISCLAMER: If it does not skip the ad, just reload the page and try again. 

// Dark Mode
javascript: if (typeof all === 'undefined') {let all = [];}all = document.getElementsByTagName('*');for (let i = 0; i < all.length; i++) document.getElementsByTagName("html")[0].style.filter = "invert()"; if (typeof elems === 'undefined') {let elems = [];}elems = document.querySelectorAll(" a, img, video, .btn-full-width, .btn-common-play-game-lg, .btn-primary-md, .btn-min-width, .ad, .adp, .banner, .ng-scope, .ng-isolate-scope, button ");for (let j = 0 ; j < elems.length; j++) {if((elems[j].nodeName == "A" && (elems[j].style.background != "" || elems[j].style.backgroundImage != "")) || elems[j].nodeName != "A"){elems[j].style.filter = "invert()";}}void 0;
// Sometimes it might not work and might be creepy.

// Edit any website
javascript:  document.body.contentEditable = true;  let all_links = document.getElementsByTagName("a");   for(let i=0; i<all_links.length; i++){     all_links[i].removeAttribute("href"); }  void 0;
// You don't actually edit EVERY website.

// Notepad
data:text/html;charset=utf-8,%0A<html>%0A<head> <title>My text editor</title>%0A<style>%0Abody{height: 80vh;background:%232E2E2E;padding: 1.5rem; margin: 0;}%0Adiv:focus{ outline: none; }%0A.editor { background: %231E1E1E; height: 90%; width: 90%; border-radius: 10px; padding: 1rem; overflow: scroll; max-height:80%; font-family: Courier New; font-weight:bold; color:%23FFFFFF; font-size:1rem;  line-height:1.4;  max-width:90%;  height: 90%;  max-height:90%;  margin:0 auto;  }  %0A.editor::before { counter-reset: listing; }%0A.editor div { counter-increment: listing; }%0A.editor div::before { color: %23555; white-space: pre-wrap;  content: counter(listing) ". ";  display: inline-block;  width: 3em;  padding-left: auto;  margin-left: auto;  text-align: right; }  %0A.buttons {  padding-left: 5%;  padding-right: 5%;  padding-top: 0.5rem;  padding-bottom: 0.5rem;  }  %0Abutton { background: %23555;  color: %23EEE;  font-family: Courier New;  font-weight:bold;  padding: 8px 16px;  border-radius: 5px;  text-align: center;  font-size: 16px;  margin: 4px 2px;  opacity: 0.6;  transition: 0.3s;  display: inline-block;  text-decoration: none;  cursor: pointer;  }  %0Abutton:hover {opacity: 1}%0A::-webkit-scrollbar { height: 0px;  width: 20px;  background-color: %23222; }%0A::-webkit-scrollbar-thumb { background-color: %235E5E5E;  border-radius: 20px;  border: 6px solid transparent;  background-clip: content-box; }%0A</style>%0A</head>%0A<body>%0A<div class="editor" spellcheck="false"> <div contenteditable="true"> </div> </div>%0A<div class="buttons"> <button onclick="downloadContent(1)">Save</button> <button onclick="changeFontSize(2)">Text Size +</button> <button onclick="changeFontSize(-2)">Text Size -</button> </div>%0A<script>%0Afunction changeFontSize(val){ let txt = document.getElementsByClassName('editor')[0]; let style = window.getComputedStyle(txt).getPropertyValue('font-size'); let currentSize = parseFloat(style); txt.style.fontSize = (currentSize + val) + 'px'; }%0Afunction downloadContent(tmp){ let a = document.body.appendChild(document.createElement("a")); let today = new Date(); let date = today.getFullYear()+'-'+(today.getMonth()+1)+'-'+today.getDate() + "-" + today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds(); a.download = "export" + date.toString() + ".txt"; let textToSave = document.getElementsByClassName("editor")[0]; a.href = "data:text/plain;charset=utf-8," + textToSave.innerText; a.click(); }%0A</script>%0A</body>%0A</html>
// You can also add HTML as a bookmarklet. Javascript is "javascript:", and HTML is "data:".

//That's basically all I have lol.
